name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test
      - name: Report coverage
        run: |
          curl -Lo ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
