name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    if: ${{ github.repository_owner == 'maxmilton' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check valid version tag
        run: |
          [[ "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-next.[0-9]+)? ]] || exit 1
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run lint
      - run: bun run test
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org"
      - name: Determine npm tag
        run: |
          if [[ "$GITHUB_REF" == *"-next."* ]]; then
            echo "NPM_TAG=next" >> $GITHUB_ENV
          else
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          fi
      - run: npm publish --provenance --access public --tag ${{ env.NPM_TAG }}
        shell: bash
